// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_s_h>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_s_h", <cbt:tetraschrabadic_trinaquadium_wire_s_h> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_s_v>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER", <cbt:tetraschrabadic_trinaquadium_wire_s_v> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_d_v>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_s_v", <cbt:tetraschrabadic_trinaquadium_wire_d_v> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_d_h>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_d_h", <cbt:tetraschrabadic_trinaquadium_wire_d_h> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_4way_ae_s>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_4way_ae_s", <cbt:tetraschrabadic_trinaquadium_wire_4way_ae_s> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_4way_ae_d>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_4way_ae_d", <cbt:tetraschrabadic_trinaquadium_wire_4way_ae_d> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos1>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_s_pos1", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos1> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos2>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_s_pos2", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos2> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos3>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_s_pos3", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos3> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos4>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_s_pos4", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_s_pos4> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos1>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_d_pos1", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos1> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos2>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_d_pos2", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos2> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos3>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_d_pos3", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos3> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos4>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_3way_ae_d_pos4", <cbt:tetraschrabadic_trinaquadium_wire_3way_ae_d_pos4> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos1>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_s_pos1", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos1> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos2>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_s_pos2", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos2> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos3>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_s_pos3", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos3> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos4>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_s_pos4", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_s_pos4> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos1>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_d_pos1", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos1> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos2>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_d_pos2", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos2> * 64, [[null, null, null, null, null, null, null, null, null], [null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos3>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_d_pos3", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos3> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos4>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_corner_ae_d_pos4", <cbt:tetraschrabadic_trinaquadium_wire_corner_ae_d_pos4> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_4way_ue_sd_pos1>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_4way_ue_sd_pos1", <cbt:tetraschrabadic_trinaquadium_wire_4way_ue_sd_pos1> * 64, [[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null], [null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null],[null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null]]);

// Shaped Tetrschrabadic Trinaquidium Wire
recipes.remove(<cbt:tetraschrabadic_trinaquadium_wire_4way_ue_sd_pos2>);
mods.avaritia.ExtremeCrafting.addShaped("tetraschrabadic_trinaquadium_wire_4way_ue_sd_pos2", <cbt:tetraschrabadic_trinaquadium_wire_4way_ue_sd_pos2> * 64, [[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null], [null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[<cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, <cbt:tetraschrabadic_trinaquadium_wireunformatted>],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null],[null, null, null, null, <cbt:tetraschrabadic_trinaquadium_wireunformatted>, null, null, null, null]]);

